# Site
repository: zhsks311/zhsks311.github.io
# favicon: images/favicon.ico

# Personal info
name: 김재휘
title: Java  백엔드 엔지니어
email: zhsks311@gmail.com

# Social links
# twitter_username: zhksks311
github_username: zhsks311
# dribbble_username: jekyll
# facebook_username: zhksks311
# flickr_username: jekyll
# linkedin_username: zhksks311
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  C#을 이용한 윈도우 어플리케이션을 시작으로 개발을 하여 Java,
  Spring Boot로 백엔드 개발을 하고 있습니다. <br />
  현재 십일번가에서 전시 서비스 개발을 하고 있습니다. <br />
  함께 일하고 싶은 개발자가 되고 싶어 동료들의 장점들을 보고
  배우려 노력합니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

# Build settings
remote_theme: sproogen/resume-theme
future: true
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
