# Site
repository: zhsks311/zhsks311.github.io
# favicon: images/favicon.ico

# Personal info
name: 김재휘
title: Java  백엔드 엔지니어
email: zhsks311@gmail.com

# Social links
# twitter_username: zhksks311
github_username: zhsks311
# dribbble_username: jekyll
# facebook_username: zhksks311
# flickr_username: jekyll
# linkedin_username: zhksks311
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  C#을 이용한 윈도우 어플리케이션을 시작으로 개발을 하여 Java,
  Spring Boot로 백엔드 개발을 하고 있습니다. <br />
  현재 십일번가에서 전시 서비스 개발을 하고 있습니다. <br />
  함께 일하고 싶은 개발자가 되고 싶어 동료들의 장점들을 보고
  배우려 노력합니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 주제로 발표와 기고, 출판을 해왔습니다.
   - [우아콘2020 - 수십억건에서 Querydsl 사용하기](https://www.youtube.com/watch?v=zMAX7g6rO_Y)
   - [스프링 부트와 AWS로 혼자 구현하는 웹 서비스](https://jojoldu.tistory.com/463)
   - [EO 인터뷰](https://www.youtube.com/watch?v=V9AGvwPmnZU&t=2s)
   - [2019 우아한 스프링 배치](https://www.youtube.com/watch?v=_nkJkWVH-mo&t=14s)
   - [인프런 - IntelliJ IDEA 가이드](https://www.inflearn.com/course/intellij-guide)
   - [2018 KCD - IntelliJ IDEA만으로 개발하기](https://www.youtube.com/watch?v=wBXSUdT1jX0)
   - [2018 JetBrains Day - Upsource를 이용한 코드리뷰](https://www.youtube.com/watch?v=06bJt6CnRAU&feature=youtu.be)
   - [마소 394호 - AWS EC2와 TravisCI를 활용한 무중단 배포 서비스](http://it.chosun.com/site/data/html_dir/2018/10/29/2018102900482.html)

# Build settings
remote_theme: sproogen/resume-theme
future: true
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
